{
    "url": "https://api.github.com/repos/dask/dask/issues/5159",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/5159/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/5159/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/5159/events",
    "html_url": "https://github.com/dask/dask/issues/5159",
    "id": 473431763,
    "node_id": "MDU6SXNzdWU0NzM0MzE3NjM=",
    "number": 5159,
    "title": "MemoryError while to_parquet or .repartition ",
    "user": {
        "login": "matthewgson",
        "id": 46496637,
        "node_id": "MDQ6VXNlcjQ2NDk2NjM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/46496637?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/matthewgson",
        "html_url": "https://github.com/matthewgson",
        "followers_url": "https://api.github.com/users/matthewgson/followers",
        "following_url": "https://api.github.com/users/matthewgson/following{/other_user}",
        "gists_url": "https://api.github.com/users/matthewgson/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/matthewgson/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/matthewgson/subscriptions",
        "organizations_url": "https://api.github.com/users/matthewgson/orgs",
        "repos_url": "https://api.github.com/users/matthewgson/repos",
        "events_url": "https://api.github.com/users/matthewgson/events{/privacy}",
        "received_events_url": "https://api.github.com/users/matthewgson/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 242862289,
            "node_id": "MDU6TGFiZWwyNDI4NjIyODk=",
            "url": "https://api.github.com/repos/dask/dask/labels/dataframe",
            "name": "dataframe",
            "color": "fbca04",
            "default": false,
            "description": null
        },
        {
            "id": 365513534,
            "node_id": "MDU6TGFiZWwzNjU1MTM1MzQ=",
            "url": "https://api.github.com/repos/dask/dask/labels/io",
            "name": "io",
            "color": "6f871c",
            "default": false,
            "description": ""
        },
        {
            "id": 2949099791,
            "node_id": "MDU6TGFiZWwyOTQ5MDk5Nzkx",
            "url": "https://api.github.com/repos/dask/dask/labels/parquet",
            "name": "parquet",
            "color": "77A66C",
            "default": false,
            "description": ""
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2019-07-26T16:07:01Z",
    "updated_at": "2021-10-13T00:32:12Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "I'm running into a MemoryError when I try to save in a parquet format, or repartition(by size).\r\nI didn't have this issue before, but after merging two dask dataframes, it's giving me this error.\r\nThe memory usage of python terminal keeps going up, and the it takes most of my machine's memory even after the error.\r\n\r\n```\r\nEWQ = dd.read_parquet('./merged1.parquet')\r\nR = dd.read_parquet('./price.parquet')\r\nprint(EWQ.npartitions);print(R.npartitions)#500, 207 each\r\nEWQR = dd.merge(EWQ, R, on = 'Symbol', how='left')\r\nEWQR.npartitions # 500 partitions\r\n\r\nwith ProgressBar():\r\n    EWQR.to_parquet('./merged2.parquet')\r\n[########################                ] | 61% Completed | 16min 49.2s\r\n\r\nTraceback (most recent call last):\r\n  File \"<input>\", line 2, in <module>\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\dataframe\\core.py\", line 3618, in to_parquet\r\n    return to_parquet(self, path, *args, **kwargs)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\dataframe\\io\\parquet.py\", line 1496, in to_parquet\r\n    out.compute()\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\base.py\", line 175, in compute\r\n    (result,) = compute(self, traverse=False, **kwargs)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\base.py\", line 446, in compute\r\n    results = schedule(dsk, keys, **kwargs)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\threaded.py\", line 82, in get\r\n    **kwargs\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\local.py\", line 491, in get_async\r\n    raise_exception(exc, tb)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\compatibility.py\", line 130, in reraise\r\n    raise exc\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\local.py\", line 233, in execute_task\r\n    result = _execute_task(task, data)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\r\n    return func(*args2)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\compatibility.py\", line 107, in apply\r\n    return func(*args, **kwargs)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\dask\\dataframe\\multi.py\", line 224, in merge_chunk\r\n    out = lhs.merge(*args, **kwargs)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\pandas\\core\\frame.py\", line 6868, in merge\r\n    copy=copy, indicator=indicator, validate=validate)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\pandas\\core\\reshape\\merge.py\", line 48, in merge\r\n    return op.get_result()\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\pandas\\core\\reshape\\merge.py\", line 546, in get_result\r\n    join_index, left_indexer, right_indexer = self._get_join_info()\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\pandas\\core\\reshape\\merge.py\", line 756, in _get_join_info\r\n    right_indexer) = self._get_join_indexers()\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\pandas\\core\\reshape\\merge.py\", line 735, in _get_join_indexers\r\n    how=self.how)\r\n  File \"C:\\Users\\gunsu.son\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\pandas\\core\\reshape\\merge.py\", line 1146, in _get_join_indexers\r\n    return join_func(lkey, rkey, count, **kwargs)\r\n  File \"pandas/_libs/join.pyx\", line 98, in pandas._libs.join.left_outer_join\r\nMemoryError\r\n\r\n```\r\n\r\nOne thing I'm a little bit suspicious about is that merged1.parquet file is unevenly partitioned in terms of size. It was partitioned into 500 files, but when I look at the size of each, some partitions have only 23KB, while some others have >500MB. I'm uncertain if this has to do with the error through. What possibly is causing the problem? How can I evade MemoryError in this case?\r\n\r\n",
    "closed_by": {
        "login": "matthewgson",
        "id": 46496637,
        "node_id": "MDQ6VXNlcjQ2NDk2NjM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/46496637?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/matthewgson",
        "html_url": "https://github.com/matthewgson",
        "followers_url": "https://api.github.com/users/matthewgson/followers",
        "following_url": "https://api.github.com/users/matthewgson/following{/other_user}",
        "gists_url": "https://api.github.com/users/matthewgson/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/matthewgson/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/matthewgson/subscriptions",
        "organizations_url": "https://api.github.com/users/matthewgson/orgs",
        "repos_url": "https://api.github.com/users/matthewgson/repos",
        "events_url": "https://api.github.com/users/matthewgson/events{/privacy}",
        "received_events_url": "https://api.github.com/users/matthewgson/received_events",
        "type": "User",
        "site_admin": false
    },
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/5159/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/5159/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}