{
    "url": "https://api.github.com/repos/dask/dask/issues/10465",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/10465/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/10465/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/10465/events",
    "html_url": "https://github.com/dask/dask/issues/10465",
    "id": 1867127708,
    "node_id": "I_kwDOAbcwm85vShuc",
    "number": 10465,
    "title": "ParserError: Error tokenizing data. C error: EOF inside string starting at row",
    "user": {
        "login": "duarteharris",
        "id": 10074430,
        "node_id": "MDQ6VXNlcjEwMDc0NDMw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10074430?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/duarteharris",
        "html_url": "https://github.com/duarteharris",
        "followers_url": "https://api.github.com/users/duarteharris/followers",
        "following_url": "https://api.github.com/users/duarteharris/following{/other_user}",
        "gists_url": "https://api.github.com/users/duarteharris/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/duarteharris/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/duarteharris/subscriptions",
        "organizations_url": "https://api.github.com/users/duarteharris/orgs",
        "repos_url": "https://api.github.com/users/duarteharris/repos",
        "events_url": "https://api.github.com/users/duarteharris/events{/privacy}",
        "received_events_url": "https://api.github.com/users/duarteharris/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 1342320181,
            "node_id": "MDU6TGFiZWwxMzQyMzIwMTgx",
            "url": "https://api.github.com/repos/dask/dask/labels/needs%20info",
            "name": "needs info",
            "color": "d0cfcc",
            "default": false,
            "description": "Needs further information from the user"
        },
        {
            "id": 3468123446,
            "node_id": "LA_kwDOAbcwm87Ot102",
            "url": "https://api.github.com/repos/dask/dask/labels/needs%20attention",
            "name": "needs attention",
            "color": "6d626c",
            "default": false,
            "description": "It's been a while since this was pushed on. Needs attention from the owner or a maintainer."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2023-08-25T14:09:15Z",
    "updated_at": "2023-09-25T01:45:29Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "Hello. \r\n\r\nTesting out Dask to help me deal with over 46M rows of data. I'm loading it like so:\r\n\r\n`dask_df = dd.read_csv(FILE_PATH)`\r\n\r\nand when I, for example, look at the head I see the head of the DataFrame:\r\n\r\n`dask_df.head()`\r\n\r\nso far so good. \r\n\r\nBut when I try to do any action that requires computation I'm getting the following error:\r\n\r\n> ParserError: Error tokenizing data. C error: EOF inside string starting at row 325771\r\n\r\nIt doesn't matter what it is.\r\n\r\nWhen I open the same dataset with pandas:\r\n\r\n`pd.read_csv(FILE_PATH)`\r\n\r\nI get no issues. I look at the row mentioned in the error message (325_771) and find nothing wrong with it. Same with the previous and next row (just to make sure).\r\n\r\nThere are **8 columns** in the dataset that pandas is interpreting the first **6 as objects** and the last **2 as int64**, 'though more precisely **4 could be str**, **2 are lat/long geodata**, and **the 2 int64 could be bool**. \r\n\r\nThe **4 columns that could be str contain information in many different languages**, including in row 325_771, and **different alphabets** (not the case in row 325_771).\r\n\r\nNot sure if it's the **encodings**, the **lat/long geodata**, or **something else**, but any idea to test as to how to solve/deal with this would be appreciated.\r\n\r\nAnything else I can provide that can be of assistance (except for the data :/), let me know.\r\n\r\nThank you,\r\n\r\n**Environment**:\r\n\r\n- Dask version: 2023.6.0\r\n- Python version: 3.11.4 (main, Jul  5 2023, 08:41:25) [Clang 14.0.6 ]\r\n- Operating System: macOS Ventura 13.4.1 (c) (22F770820d)\r\n- Install method (conda, pip, source): conda\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/10465/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/10465/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}