{
    "url": "https://api.github.com/repos/dask/dask/issues/10545",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/10545/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/10545/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/10545/events",
    "html_url": "https://github.com/dask/dask/issues/10545",
    "id": 1927080273,
    "node_id": "I_kwDOAbcwm85y3OlR",
    "number": 10545,
    "title": "\"Failed to deserialize\" when using dd.from_delayed on pd.read_sql-generated DFs",
    "user": {
        "login": "arjun-shanmugam",
        "id": 65803362,
        "node_id": "MDQ6VXNlcjY1ODAzMzYy",
        "avatar_url": "https://avatars.githubusercontent.com/u/65803362?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/arjun-shanmugam",
        "html_url": "https://github.com/arjun-shanmugam",
        "followers_url": "https://api.github.com/users/arjun-shanmugam/followers",
        "following_url": "https://api.github.com/users/arjun-shanmugam/following{/other_user}",
        "gists_url": "https://api.github.com/users/arjun-shanmugam/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/arjun-shanmugam/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/arjun-shanmugam/subscriptions",
        "organizations_url": "https://api.github.com/users/arjun-shanmugam/orgs",
        "repos_url": "https://api.github.com/users/arjun-shanmugam/repos",
        "events_url": "https://api.github.com/users/arjun-shanmugam/events{/privacy}",
        "received_events_url": "https://api.github.com/users/arjun-shanmugam/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 3468123446,
            "node_id": "LA_kwDOAbcwm87Ot102",
            "url": "https://api.github.com/repos/dask/dask/labels/needs%20attention",
            "name": "needs attention",
            "color": "6d626c",
            "default": false,
            "description": "It's been a while since this was pushed on. Needs attention from the owner or a maintainer."
        },
        {
            "id": 3880424463,
            "node_id": "LA_kwDOAbcwm87nSpQP",
            "url": "https://api.github.com/repos/dask/dask/labels/needs%20triage",
            "name": "needs triage",
            "color": "eeeeee",
            "default": false,
            "description": "Needs a response from a contributor"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2023-10-04T22:38:04Z",
    "updated_at": "2023-11-13T01:46:29Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "**Describe the issue**:\r\nI'm currently trying to read from a database in parallel using Dask and Pandas. I'm creating a collection of Dask delayed objects using pd.read_sql and then using Dask's from_delayed method to produce a Dask DataFrame. Unfortunately I'm working with a secure database so I can't provide a copy/paste-able example, but the following code comes pretty close:\r\n\r\n**Minimal Complete Verifiable Example**:\r\n```\r\nimport dask.dataframe as dd\r\nfrom dask.delayed import delayed\r\nimport pandas as pd\r\nimport pyodbc\r\nfrom sqlalchemy.engine import URL\r\n\r\ndef load_table_in_parallel(metadata, table_name, index_column):\r\n\r\n    # Construct database connection URI and create engine\r\n    connection_uri = \"sybaseiq://username:password@XX.XX.XX.XX:XXXX/XXX\"\r\n   engine = create_engine(connection_uri)\r\n\r\n    # Create column metadata\r\n    dd.utils.make_meta(pd.read_sql_query(f\"SELECT TOP 1 * FROM {table_name}\", \r\n                                         connection_uri))\r\n\r\n    # Create Table object that reflects requested database table\r\n    table = Table(table_name, metadata, autoload_with_engine, quote=False)\r\n    \r\n    return dd.read_sql_query(select(table),\r\n                             connection_uri,\r\n                             index_column,\r\n                             npartitions=16,\r\n                             meta=meta,\r\n                             head_rows=0)\r\n\r\n# This line is where the error occurs\r\nload_table_in_parallel().compute()\r\n                                         \r\n                                             \r\n```\r\n\r\nI get a long error message (which I can't export due to privacy restrictions) which begins with \"Failed to deserialize\" and ends with \"CanceledError: ('from-delayed-c9f959ldkjfd8032a', 1)\"\r\n\r\n**Environment**:\r\n\r\n- Dask version: 2023.6.0\r\n- Python version: 3.11.3\r\n- Operating System: RedHat Linux\r\n- Install method (conda, pip, source): Conda \r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/10545/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/10545/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}