[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/510575334",
        "html_url": "https://github.com/dask/dask/issues/5087#issuecomment-510575334",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5087",
        "id": 510575334,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMDU3NTMzNA==",
        "user": {
            "login": "quasiben",
            "id": 1403768,
            "node_id": "MDQ6VXNlcjE0MDM3Njg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1403768?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/quasiben",
            "html_url": "https://github.com/quasiben",
            "followers_url": "https://api.github.com/users/quasiben/followers",
            "following_url": "https://api.github.com/users/quasiben/following{/other_user}",
            "gists_url": "https://api.github.com/users/quasiben/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/quasiben/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/quasiben/subscriptions",
            "organizations_url": "https://api.github.com/users/quasiben/orgs",
            "repos_url": "https://api.github.com/users/quasiben/repos",
            "events_url": "https://api.github.com/users/quasiben/events{/privacy}",
            "received_events_url": "https://api.github.com/users/quasiben/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-11T17:17:42Z",
        "updated_at": "2019-07-11T17:17:42Z",
        "author_association": "MEMBER",
        "body": "I am not sure this is a bug.  If the scheduler is not addressable by remote workers then there is not much dask can do.  This would be true if using `localhost` or `127.0.0.1`.  What would you expect dask to do differently here ?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/510575334/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/510578224",
        "html_url": "https://github.com/dask/dask/issues/5087#issuecomment-510578224",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5087",
        "id": 510578224,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMDU3ODIyNA==",
        "user": {
            "login": "landonzweigle",
            "id": 44909659,
            "node_id": "MDQ6VXNlcjQ0OTA5NjU5",
            "avatar_url": "https://avatars.githubusercontent.com/u/44909659?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/landonzweigle",
            "html_url": "https://github.com/landonzweigle",
            "followers_url": "https://api.github.com/users/landonzweigle/followers",
            "following_url": "https://api.github.com/users/landonzweigle/following{/other_user}",
            "gists_url": "https://api.github.com/users/landonzweigle/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/landonzweigle/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/landonzweigle/subscriptions",
            "organizations_url": "https://api.github.com/users/landonzweigle/orgs",
            "repos_url": "https://api.github.com/users/landonzweigle/repos",
            "events_url": "https://api.github.com/users/landonzweigle/events{/privacy}",
            "received_events_url": "https://api.github.com/users/landonzweigle/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-11T17:25:57Z",
        "updated_at": "2019-07-11T17:25:57Z",
        "author_association": "NONE",
        "body": "I see. I was thinking localhost could be resolved to a public address, such as the address given by if/ipconfig. Getting an actual public address might require a call to some external API or something. Sorry if I am wrong about this, I am not super familiar with networking and as such didn't give it much thought other than \"huh, that doesn't seem right\".",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/510578224/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/510590782",
        "html_url": "https://github.com/dask/dask/issues/5087#issuecomment-510590782",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5087",
        "id": 510590782,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMDU5MDc4Mg==",
        "user": {
            "login": "quasiben",
            "id": 1403768,
            "node_id": "MDQ6VXNlcjE0MDM3Njg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1403768?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/quasiben",
            "html_url": "https://github.com/quasiben",
            "followers_url": "https://api.github.com/users/quasiben/followers",
            "following_url": "https://api.github.com/users/quasiben/following{/other_user}",
            "gists_url": "https://api.github.com/users/quasiben/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/quasiben/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/quasiben/subscriptions",
            "organizations_url": "https://api.github.com/users/quasiben/orgs",
            "repos_url": "https://api.github.com/users/quasiben/repos",
            "events_url": "https://api.github.com/users/quasiben/events{/privacy}",
            "received_events_url": "https://api.github.com/users/quasiben/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-11T18:00:05Z",
        "updated_at": "2019-07-11T18:00:05Z",
        "author_association": "MEMBER",
        "body": "@landonzweigle , I agree, this is annoying when you want to resolve localhost to the *most* available address.  This is somewhat challenging in many if not most cases -- my machine right now has a few IPs: 127.0.0.1, internal ip 192.168.xxx, and it's also addressable because of router configurations allowing connections on XXXXX for the global address for my office/home/etc.  You can see this with `socket`:\r\n\r\n```python\r\nimport socket\r\nsocket.gethostbyname(socket.gethostname()) # will probably return 127.0.0.1\r\n\r\nimport socket\r\ns = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)\r\ns.connect((\"8.8.8.8\", 80))\r\nprint(s.getsockname()[0]) # probably internal ip\r\ns.close()\r\n```\r\n\r\nYou can also see all this info with `ifconfig or /sbin/ifconfig` (if on OSX/Linux).  The problem may even be worse with several attached network cards or other devices which expose network interfaces.\r\n\r\nSo with all that said, many systems offload this problem to the user and let them define where the connection should happen (locahost, private ip, global address, k8s internal address, etc).  Still, I agree this is a rather annoying problem which takes away 10s of minutes to hours from users when trying to debug unfamiliar networking issues.  ",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/510590782/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/510608820",
        "html_url": "https://github.com/dask/dask/issues/5087#issuecomment-510608820",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5087",
        "id": 510608820,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMDYwODgyMA==",
        "user": {
            "login": "landonzweigle",
            "id": 44909659,
            "node_id": "MDQ6VXNlcjQ0OTA5NjU5",
            "avatar_url": "https://avatars.githubusercontent.com/u/44909659?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/landonzweigle",
            "html_url": "https://github.com/landonzweigle",
            "followers_url": "https://api.github.com/users/landonzweigle/followers",
            "following_url": "https://api.github.com/users/landonzweigle/following{/other_user}",
            "gists_url": "https://api.github.com/users/landonzweigle/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/landonzweigle/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/landonzweigle/subscriptions",
            "organizations_url": "https://api.github.com/users/landonzweigle/orgs",
            "repos_url": "https://api.github.com/users/landonzweigle/repos",
            "events_url": "https://api.github.com/users/landonzweigle/events{/privacy}",
            "received_events_url": "https://api.github.com/users/landonzweigle/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-11T18:49:44Z",
        "updated_at": "2019-07-11T18:50:14Z",
        "author_association": "NONE",
        "body": "> Still, I agree this is a rather annoying problem which takes away 10s of minutes to hours from users when trying to debug unfamiliar networking issues.\r\n\r\nI was thinking simply warn the user if the address can't be resolved (or something...). I was also thinking that if localhost is used, tell the workers that the connection that was used to initialize them is the same connection as the scheduler (because some communication with \"localhost\" had to be made, right?)... I really have no idea how you do things with setting up workers, so maybe this wouldn't work or would take longer to implement than a simple external api (ipify).",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/510608820/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/511883050",
        "html_url": "https://github.com/dask/dask/issues/5087#issuecomment-511883050",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5087",
        "id": 511883050,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMTg4MzA1MA==",
        "user": {
            "login": "quasiben",
            "id": 1403768,
            "node_id": "MDQ6VXNlcjE0MDM3Njg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1403768?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/quasiben",
            "html_url": "https://github.com/quasiben",
            "followers_url": "https://api.github.com/users/quasiben/followers",
            "following_url": "https://api.github.com/users/quasiben/following{/other_user}",
            "gists_url": "https://api.github.com/users/quasiben/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/quasiben/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/quasiben/subscriptions",
            "organizations_url": "https://api.github.com/users/quasiben/orgs",
            "repos_url": "https://api.github.com/users/quasiben/repos",
            "events_url": "https://api.github.com/users/quasiben/events{/privacy}",
            "received_events_url": "https://api.github.com/users/quasiben/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-16T16:10:24Z",
        "updated_at": "2019-07-16T16:10:24Z",
        "author_association": "MEMBER",
        "body": "@jcrist do you have thoughts here ?  My opinion is that while the log comment:\r\n\r\n> Waiting to connect to: tcp://localhost:8786\r\n\r\nis not an explicit comment saying unable to resolve host a user could (should?) infer it ?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/511883050/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/511886644",
        "html_url": "https://github.com/dask/dask/issues/5087#issuecomment-511886644",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5087",
        "id": 511886644,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMTg4NjY0NA==",
        "user": {
            "login": "jcrist",
            "id": 2783717,
            "node_id": "MDQ6VXNlcjI3ODM3MTc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2783717?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jcrist",
            "html_url": "https://github.com/jcrist",
            "followers_url": "https://api.github.com/users/jcrist/followers",
            "following_url": "https://api.github.com/users/jcrist/following{/other_user}",
            "gists_url": "https://api.github.com/users/jcrist/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jcrist/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jcrist/subscriptions",
            "organizations_url": "https://api.github.com/users/jcrist/orgs",
            "repos_url": "https://api.github.com/users/jcrist/repos",
            "events_url": "https://api.github.com/users/jcrist/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jcrist/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-16T16:20:01Z",
        "updated_at": "2019-07-16T16:20:01Z",
        "author_association": "MEMBER",
        "body": "> I was thinking localhost could be resolved to a public address, such as the address given by if/ipconfig.\r\n\r\nWhile we could make an attempt at this, it's not the safest approach. What if the user really meant localhost rather than something publically addressable? What if they use another loopback address? I'd rather not guess the user's intent, and fix this with documentation/better logging.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/511886644/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/512491154",
        "html_url": "https://github.com/dask/dask/issues/5087#issuecomment-512491154",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5087",
        "id": 512491154,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMjQ5MTE1NA==",
        "user": {
            "login": "jrbourbeau",
            "id": 11656932,
            "node_id": "MDQ6VXNlcjExNjU2OTMy",
            "avatar_url": "https://avatars.githubusercontent.com/u/11656932?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jrbourbeau",
            "html_url": "https://github.com/jrbourbeau",
            "followers_url": "https://api.github.com/users/jrbourbeau/followers",
            "following_url": "https://api.github.com/users/jrbourbeau/following{/other_user}",
            "gists_url": "https://api.github.com/users/jrbourbeau/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jrbourbeau/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jrbourbeau/subscriptions",
            "organizations_url": "https://api.github.com/users/jrbourbeau/orgs",
            "repos_url": "https://api.github.com/users/jrbourbeau/repos",
            "events_url": "https://api.github.com/users/jrbourbeau/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jrbourbeau/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-17T17:49:03Z",
        "updated_at": "2019-07-17T17:49:03Z",
        "author_association": "MEMBER",
        "body": "> fix this with documentation/better logging\r\n\r\n@landonzweigle do you an interest in submitting a PR? (no obligation though)",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/512491154/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/513220159",
        "html_url": "https://github.com/dask/dask/issues/5087#issuecomment-513220159",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5087",
        "id": 513220159,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMzIyMDE1OQ==",
        "user": {
            "login": "quasiben",
            "id": 1403768,
            "node_id": "MDQ6VXNlcjE0MDM3Njg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1403768?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/quasiben",
            "html_url": "https://github.com/quasiben",
            "followers_url": "https://api.github.com/users/quasiben/followers",
            "following_url": "https://api.github.com/users/quasiben/following{/other_user}",
            "gists_url": "https://api.github.com/users/quasiben/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/quasiben/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/quasiben/subscriptions",
            "organizations_url": "https://api.github.com/users/quasiben/orgs",
            "repos_url": "https://api.github.com/users/quasiben/repos",
            "events_url": "https://api.github.com/users/quasiben/events{/privacy}",
            "received_events_url": "https://api.github.com/users/quasiben/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-19T13:02:25Z",
        "updated_at": "2019-07-19T13:02:25Z",
        "author_association": "MEMBER",
        "body": "@landonzweigle one possibility is that after N attempts the message could change from:\r\n> Waiting to connect to: tcp://localhost:8786\r\n\r\nto something more informative/exploratory:\r\n\r\n> Connection to: tcp://localhost:8786 is still waiting -- user should confirm host is addressable by worker \r\n\r\n@landonzweigle, I would also say that error messages can be difficult to craft.  Thank you for raising this issue and it's more than likely you are not the only person to have experienced this problem\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/513220159/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]