[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/2131339464",
        "html_url": "https://github.com/dask/dask/issues/11146#issuecomment-2131339464",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/11146",
        "id": 2131339464,
        "node_id": "IC_kwDOAbcwm85_CajI",
        "user": {
            "login": "phofl",
            "id": 61934744,
            "node_id": "MDQ6VXNlcjYxOTM0NzQ0",
            "avatar_url": "https://avatars.githubusercontent.com/u/61934744?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/phofl",
            "html_url": "https://github.com/phofl",
            "followers_url": "https://api.github.com/users/phofl/followers",
            "following_url": "https://api.github.com/users/phofl/following{/other_user}",
            "gists_url": "https://api.github.com/users/phofl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/phofl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/phofl/subscriptions",
            "organizations_url": "https://api.github.com/users/phofl/orgs",
            "repos_url": "https://api.github.com/users/phofl/repos",
            "events_url": "https://api.github.com/users/phofl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/phofl/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-25T16:27:51Z",
        "updated_at": "2024-05-25T16:27:51Z",
        "author_association": "MEMBER",
        "body": "Thanks for the report.\r\n\r\nCould you add a bit more context about what you are trying to achieve with attr? attr doesn't really work in pandas either and support is spotty at most.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/2131339464/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/2133910953",
        "html_url": "https://github.com/dask/dask/issues/11146#issuecomment-2133910953",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/11146",
        "id": 2133910953,
        "node_id": "IC_kwDOAbcwm85_MOWp",
        "user": {
            "login": "LucaMarconato",
            "id": 2664412,
            "node_id": "MDQ6VXNlcjI2NjQ0MTI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2664412?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/LucaMarconato",
            "html_url": "https://github.com/LucaMarconato",
            "followers_url": "https://api.github.com/users/LucaMarconato/followers",
            "following_url": "https://api.github.com/users/LucaMarconato/following{/other_user}",
            "gists_url": "https://api.github.com/users/LucaMarconato/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/LucaMarconato/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/LucaMarconato/subscriptions",
            "organizations_url": "https://api.github.com/users/LucaMarconato/orgs",
            "repos_url": "https://api.github.com/users/LucaMarconato/repos",
            "events_url": "https://api.github.com/users/LucaMarconato/events{/privacy}",
            "received_events_url": "https://api.github.com/users/LucaMarconato/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-27T18:22:17Z",
        "updated_at": "2024-05-27T18:22:17Z",
        "author_association": "NONE",
        "body": "I also experienced a problem with `pandas` and `.attrs`: copied `DataFrame` objects where not containing a copy of `.attrs`. (I initially thought it was a `geopandas` problem https://github.com/geopandas/geopandas/issues/2920), but then it turned out to be from `pandas` https://github.com/pandas-dev/pandas/issues/54134. Fortunately the bug above is now fixed. Which other problems did you find?\r\n\r\nThe use case for `.attrs` we have in the library we developed https://github.com/scverse/spatialdata/, is to store metadata associated to `GeoDataFrame` and `DataFrame` objects (both lazy and non-lazy). The metadata mostly contain json-like information that describes how various spatial objects are aligned together. ",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/2133910953/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/2144042909",
        "html_url": "https://github.com/dask/dask/issues/11146#issuecomment-2144042909",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/11146",
        "id": 2144042909,
        "node_id": "IC_kwDOAbcwm85_y3-d",
        "user": {
            "login": "LucaMarconato",
            "id": 2664412,
            "node_id": "MDQ6VXNlcjI2NjQ0MTI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2664412?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/LucaMarconato",
            "html_url": "https://github.com/LucaMarconato",
            "followers_url": "https://api.github.com/users/LucaMarconato/followers",
            "following_url": "https://api.github.com/users/LucaMarconato/following{/other_user}",
            "gists_url": "https://api.github.com/users/LucaMarconato/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/LucaMarconato/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/LucaMarconato/subscriptions",
            "organizations_url": "https://api.github.com/users/LucaMarconato/orgs",
            "repos_url": "https://api.github.com/users/LucaMarconato/repos",
            "events_url": "https://api.github.com/users/LucaMarconato/events{/privacy}",
            "received_events_url": "https://api.github.com/users/LucaMarconato/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-06-02T22:34:04Z",
        "updated_at": "2024-06-02T22:34:04Z",
        "author_association": "NONE",
        "body": "Do you have any update on this? \ud83d\ude0a Some users reported problems with installation due to having pinned an older version of Dask in our config so it's an important issue for us. Thank you for your time.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/2144042909/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/2152567243",
        "html_url": "https://github.com/dask/dask/issues/11146#issuecomment-2152567243",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/11146",
        "id": 2152567243,
        "node_id": "IC_kwDOAbcwm86ATZHL",
        "user": {
            "login": "phofl",
            "id": 61934744,
            "node_id": "MDQ6VXNlcjYxOTM0NzQ0",
            "avatar_url": "https://avatars.githubusercontent.com/u/61934744?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/phofl",
            "html_url": "https://github.com/phofl",
            "followers_url": "https://api.github.com/users/phofl/followers",
            "following_url": "https://api.github.com/users/phofl/following{/other_user}",
            "gists_url": "https://api.github.com/users/phofl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/phofl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/phofl/subscriptions",
            "organizations_url": "https://api.github.com/users/phofl/orgs",
            "repos_url": "https://api.github.com/users/phofl/repos",
            "events_url": "https://api.github.com/users/phofl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/phofl/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-06-06T13:45:48Z",
        "updated_at": "2024-06-06T13:45:48Z",
        "author_association": "MEMBER",
        "body": "This is non-trivial to add and the semantics aren't completely clear either. This can't live on the collection level, it has to be on the expression level since we are constantly recreating the underlying expression, which makes it non-trivial. That said, the following is unclear to me:\r\n\r\n```\r\ndf = dd.from_pandas(...)\r\ndf.attrs = \"foo\"\r\ndf = df.fillna(100)\r\ndf = df[\"a\"]\r\ndf.attrs = \"bar\"\r\n```\r\n\r\ndask-expr will reorder the query and push the projection in front of the fillna. So what attr should take precedence here?\r\n\r\nContributions are very welcome. I won't have much time to think about this though",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/2152567243/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]