[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/420998631",
        "html_url": "https://github.com/dask/dask/issues/3976#issuecomment-420998631",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/3976",
        "id": 420998631,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMDk5ODYzMQ==",
        "user": {
            "login": "jorisvandenbossche",
            "id": 1020496,
            "node_id": "MDQ6VXNlcjEwMjA0OTY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1020496?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jorisvandenbossche",
            "html_url": "https://github.com/jorisvandenbossche",
            "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
            "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
            "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
            "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
            "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
            "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-13T13:03:12Z",
        "updated_at": "2018-09-13T13:03:12Z",
        "author_association": "MEMBER",
        "body": "I can reproduce this, but I am also a bit lost about the cause at this moment (meaning: we can add a `nbytes` to GeometryArray which will solve this, but it should still not end up there). \r\n\r\nSo when calling `client.scatter(buffer)` I get the same warning, but when doing `distributed.safe_sizeof(buffer)` (which is what is getting called according to the traceback), it works fine.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/420998631/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/421001648",
        "html_url": "https://github.com/dask/dask/issues/3976#issuecomment-421001648",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/3976",
        "id": 421001648,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTAwMTY0OA==",
        "user": {
            "login": "avnovikov",
            "id": 15693459,
            "node_id": "MDQ6VXNlcjE1NjkzNDU5",
            "avatar_url": "https://avatars.githubusercontent.com/u/15693459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/avnovikov",
            "html_url": "https://github.com/avnovikov",
            "followers_url": "https://api.github.com/users/avnovikov/followers",
            "following_url": "https://api.github.com/users/avnovikov/following{/other_user}",
            "gists_url": "https://api.github.com/users/avnovikov/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/avnovikov/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/avnovikov/subscriptions",
            "organizations_url": "https://api.github.com/users/avnovikov/orgs",
            "repos_url": "https://api.github.com/users/avnovikov/repos",
            "events_url": "https://api.github.com/users/avnovikov/events{/privacy}",
            "received_events_url": "https://api.github.com/users/avnovikov/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-13T13:12:02Z",
        "updated_at": "2018-09-13T13:15:55Z",
        "author_association": "NONE",
        "body": "@TomAugspurger can you please comment on this.\r\n\r\n@jorisvandenbossche - surely I'll try my best to find what had happened. (I hate not making things fixed after spending four days trying to get to the cause\u001b and create duck tape workaround).\r\nAnd please note that this is the problem with GeoSeries, GeoDataFrame works fine.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/421001648/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/421004476",
        "html_url": "https://github.com/dask/dask/issues/3976#issuecomment-421004476",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/3976",
        "id": 421004476,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTAwNDQ3Ng==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-13T13:21:14Z",
        "updated_at": "2018-09-13T13:21:14Z",
        "author_association": "MEMBER",
        "body": "I'm not sure.\n\nOn Thu, Sep 13, 2018 at 8:12 AM avnovikov <notifications@github.com> wrote:\n\n> @TomAugspurger <https://github.com/TomAugspurger> can you please comment\n> on this.\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/dask/dask/issues/3976#issuecomment-421001648>, or mute\n> the thread\n> <https://github.com/notifications/unsubscribe-auth/ABQHIkh82rFIQC4-ZMzGoNWkpWtUi1fLks5ualmsgaJpZM4Wkvfh>\n> .\n>\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/421004476/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/421005734",
        "html_url": "https://github.com/dask/dask/issues/3976#issuecomment-421005734",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/3976",
        "id": 421005734,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTAwNTczNA==",
        "user": {
            "login": "jorisvandenbossche",
            "id": 1020496,
            "node_id": "MDQ6VXNlcjEwMjA0OTY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1020496?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jorisvandenbossche",
            "html_url": "https://github.com/jorisvandenbossche",
            "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
            "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
            "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
            "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
            "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
            "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-13T13:25:20Z",
        "updated_at": "2018-09-13T13:25:20Z",
        "author_association": "MEMBER",
        "body": "@avnovikov I think the quick fix would be to add `nbytes` to `GeometryArray` (it is still strange why we run into this issue, but adding that attribute is something that we need to do anyway to satisfy the new pandas extension interface)",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/421005734/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/431987667",
        "html_url": "https://github.com/dask/dask/issues/3976#issuecomment-431987667",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/3976",
        "id": 431987667,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzMTk4NzY2Nw==",
        "user": {
            "login": "mrocklin",
            "id": 306380,
            "node_id": "MDQ6VXNlcjMwNjM4MA==",
            "avatar_url": "https://avatars.githubusercontent.com/u/306380?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mrocklin",
            "html_url": "https://github.com/mrocklin",
            "followers_url": "https://api.github.com/users/mrocklin/followers",
            "following_url": "https://api.github.com/users/mrocklin/following{/other_user}",
            "gists_url": "https://api.github.com/users/mrocklin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mrocklin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mrocklin/subscriptions",
            "organizations_url": "https://api.github.com/users/mrocklin/orgs",
            "repos_url": "https://api.github.com/users/mrocklin/repos",
            "events_url": "https://api.github.com/users/mrocklin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mrocklin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-10-22T21:09:51Z",
        "updated_at": "2018-10-22T21:09:51Z",
        "author_association": "MEMBER",
        "body": "Any update on this?  It appears to have gone quiet.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/431987667/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]