[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/496472259",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-496472259",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 496472259,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NjQ3MjI1OQ==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-28T11:12:16Z",
        "updated_at": "2019-05-28T11:12:16Z",
        "author_association": "MEMBER",
        "body": "Note that this only happens when we have multiple threads working with the same data.\r\n\r\n```python\r\n\r\ndf['nr'] = df.groupby(['ind_a', 'ind_b']).cumcount()\r\nlen(df)\r\n\r\n\r\n```python\r\nIn [4]: dask.config.set(scheduler='multiprocessing')\r\nOut[4]: <dask.config.set at 0x113d8b208>\r\n\r\nIn [5]: df['nr'] = df.groupby(['ind_a', 'ind_b']).cumcount()\r\n   ...: len(df)\r\n   ...:\r\nOut[5]: 100\r\n\r\nIn [6]: dask.config.set(scheduler='single-threaded')\r\nOut[6]: <dask.config.set at 0x113d9ae80>\r\n\r\nIn [7]: df['nr'] = df.groupby(['ind_a', 'ind_b']).cumcount()\r\n   ...: len(df)\r\n```\r\n\r\nSeems like some piece of data is being manipulated inplace by two threads.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/496472259/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/497102835",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-497102835",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 497102835,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NzEwMjgzNQ==",
        "user": {
            "login": "jakirkham",
            "id": 3019665,
            "node_id": "MDQ6VXNlcjMwMTk2NjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jakirkham",
            "html_url": "https://github.com/jakirkham",
            "followers_url": "https://api.github.com/users/jakirkham/followers",
            "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
            "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
            "organizations_url": "https://api.github.com/users/jakirkham/orgs",
            "repos_url": "https://api.github.com/users/jakirkham/repos",
            "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jakirkham/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-29T20:47:04Z",
        "updated_at": "2019-05-29T20:47:04Z",
        "author_association": "MEMBER",
        "body": "If that's true, would it be possible to inject copies in-between steps to identify where the in-place manipulation is occurring?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/497102835/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/497705171",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-497705171",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 497705171,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NzcwNTE3MQ==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-31T13:17:29Z",
        "updated_at": "2019-05-31T13:17:29Z",
        "author_association": "MEMBER",
        "body": "I'm not sure. I think a more productive line is to demonstrate the thread safety issue with pandas-only code and a ThreadPool, and see if changes can be made to pandas. @marberi are you interested in exploring that?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/497705171/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/497708850",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-497708850",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 497708850,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NzcwODg1MA==",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-31T13:29:06Z",
        "updated_at": "2019-05-31T13:29:06Z",
        "author_association": "NONE",
        "body": "@TomAugspurger Could you outline how I could make such a test? I am quite familiar with Pandas from as a user, but not how one would debug this issue.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/497708850/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/497714918",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-497714918",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 497714918,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NzcxNDkxOA==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-31T13:47:41Z",
        "updated_at": "2019-05-31T13:47:41Z",
        "author_association": "MEMBER",
        "body": "I'm not entirely sure either. This is a bit tricky, since it's not clear\nwhat section of pandas is mutating the shared object.\n\nI would try a couple approaches:\n\n1. Use a ThreadPoolExecutor to apply multiple reductions (cumcount, commix)\nto the same DataFrameGroupBy object at the same time.\n   That would help narrow down whether the issue is in pandas' groupby\ncode, or in the indexing dask does before getting there.\n2. Try adding finer and finer-grained thread locks on the functions used as\npart of dask's cumcount.\n\nThis still may not end up finding this issue... This is a tricky one.\n\nOn Fri, May 31, 2019 at 8:29 AM marberi <notifications@github.com> wrote:\n\n> @TomAugspurger <https://github.com/TomAugspurger> Could you outline how I\n> could make such a test? I am quite familiar with Pandas from as a user, but\n> not how one would debug this issue.\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/dask/dask/issues/4845?email_source=notifications&email_token=AAKAOISAOR2GR6RHAOGROKDPYER2LA5CNFSM4HPW3SIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWVG6MQ#issuecomment-497708850>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAKAOIT4FYSGJXXE7S4GB73PYER2LANCNFSM4HPW3SIA>\n> .\n>\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/497714918/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498287508",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498287508",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498287508,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODI4NzUwOA==",
        "user": {
            "login": "jakirkham",
            "id": 3019665,
            "node_id": "MDQ6VXNlcjMwMTk2NjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jakirkham",
            "html_url": "https://github.com/jakirkham",
            "followers_url": "https://api.github.com/users/jakirkham/followers",
            "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
            "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
            "organizations_url": "https://api.github.com/users/jakirkham/orgs",
            "repos_url": "https://api.github.com/users/jakirkham/repos",
            "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jakirkham/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-03T14:45:32Z",
        "updated_at": "2019-06-03T14:45:32Z",
        "author_association": "MEMBER",
        "body": "@marberi, does Tom's suggested course of action above make sense? Do you have additional questions?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498287508/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498660962",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498660962",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498660962,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODY2MDk2Mg==",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T12:59:30Z",
        "updated_at": "2019-06-04T12:59:30Z",
        "author_association": "NONE",
        "body": "I will have a try. Tried some simple debugging this morning, inserting some print statements in the Pandas code to see if I could find some hints. Quite tricky, since the state at times changes between \"is_unique\" and checking what are duplicates. I keep looking. However, testing if upgrading Pandas to the latest version gives another issue (see attachment). Are you aware of this problem? It seems unrelated, but something which should be fixed.\r\n[new_message.txt](https://github.com/dask/dask/files/3252464/new_message.txt)\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498660962/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498666222",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498666222",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498666222,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODY2NjIyMg==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T13:14:19Z",
        "updated_at": "2019-06-04T13:14:19Z",
        "author_association": "MEMBER",
        "body": "Opened https://github.com/dask/dask/issues/4880 for that new message.\n\nhttps://github.com/pandas-dev/pandas/issues/21150 may be relevant for the\noriginal issue, but there isn't much info there.\n\nOn Tue, Jun 4, 2019 at 7:59 AM marberi <notifications@github.com> wrote:\n\n> I will have a try. Tried some simple debugging this morning, inserting\n> some print statements in the Pandas code to see if I could find some hints.\n> Quite tricky, since the state at times changes between \"is_unique\" and\n> checking what are duplicates. I keep looking. However, testing if upgrading\n> Pandas to the latest version gives another issue (see attachment). Are you\n> aware of this problem? It seems unrelated, but something which should be\n> fixed.\n> new_message.txt\n> <https://github.com/dask/dask/files/3252464/new_message.txt>\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/dask/dask/issues/4845?email_source=notifications&email_token=AAKAOIU7ZDZKE3ZQHY5DLOTPYZRLLA5CNFSM4HPW3SIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4PMYQ#issuecomment-498660962>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAKAOISF7TF5J7DAA3DVDH3PYZRLLANCNFSM4HPW3SIA>\n> .\n>\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498666222/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498672670",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498672670",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498672670,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODY3MjY3MA==",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T13:31:10Z",
        "updated_at": "2019-06-04T13:31:10Z",
        "author_association": "NONE",
        "body": "Thanks. It looks very relevant. The Pandas code called by dask crashes in multiple places, but testing with \"is_unique\" seems to always be involved.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498672670/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498677992",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498677992",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498677992,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODY3Nzk5Mg==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T13:45:11Z",
        "updated_at": "2019-06-04T13:45:11Z",
        "author_association": "MEMBER",
        "body": "Yes, I missed that earlier. You might try adding a `threading.Lock` around\nuses of is_unique / do_unique_check just to verify.\n\nOn Tue, Jun 4, 2019 at 8:31 AM marberi <notifications@github.com> wrote:\n\n> Thanks. It looks very relevant. The Pandas code called by dask crashes in\n> multiple places, but testing with \"is_unique\" seems to always be involved.\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/dask/dask/issues/4845?email_source=notifications&email_token=AAKAOIRC2VVULU3PVUA4E3LPYZVCDA5CNFSM4HPW3SIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4SIHQ#issuecomment-498672670>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAKAOIVJVNPS2YE3KQOCSRLPYZVCDANCNFSM4HPW3SIA>\n> .\n>\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498677992/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498700713",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498700713",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498700713,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODcwMDcxMw==",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T14:39:29Z",
        "updated_at": "2019-06-04T14:39:29Z",
        "author_association": "NONE",
        "body": "I tried adding a lock in \"is_unique\" in the Pandas source code, as shown below. Then\r\nrerunning I still have the same issue. Does this look like a correct usage of locking?\r\n\r\n```\r\n    @property\r\n    def is_unique(self):\r\n        import threading\r\n        lock = threading.Lock()\r\n        lock.acquire_lock()\r\n\r\n        print('is rebuilt: 2')\r\n        if self.need_unique_check:\r\n            self._do_unique_check()\r\n\r\n        ans = self.unique == 1\r\n        lock.release()\r\n\r\n        return ans\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498700713/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498702097",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498702097",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498702097,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODcwMjA5Nw==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T14:42:32Z",
        "updated_at": "2019-06-04T14:42:32Z",
        "author_association": "MEMBER",
        "body": "Yes. Pandas has multiple index classes, and some override is_unique with\ntheir own implementations.\n\nOn Tue, Jun 4, 2019 at 9:39 AM marberi <notifications@github.com> wrote:\n\n> I tried adding a lock in \"is_unique\" in the Pandas source code, as shown\n> below. Then\n> rerunning I still have the same issue. Does this look like a correct usage\n> of locking?\n>\n>     @property\n>     def is_unique(self):\n>         import threading\n>         lock = threading.Lock()\n>         lock.acquire_lock()\n>\n>         print('is rebuilt: 2')\n>         if self.need_unique_check:\n>             self._do_unique_check()\n>\n>         ans = self.unique == 1\n>         lock.release()\n>\n>         return ans\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/dask/dask/issues/4845?email_source=notifications&email_token=AAKAOITLRWXXR7YAP445JLDPYZ5CJA5CNFSM4HPW3SIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4ZDKI#issuecomment-498700713>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAKAOIROQDGLS3IPSQSI3ZDPYZ5CJANCNFSM4HPW3SIA>\n> .\n>\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498702097/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498719082",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498719082",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498719082,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODcxOTA4Mg==",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T15:22:53Z",
        "updated_at": "2019-06-04T15:22:53Z",
        "author_association": "NONE",
        "body": "Ok, I got one step further concerning this. The \"is_unique\" method in the Index class found in:\r\npandas/pandas/core/indexes/base.py\r\n\r\nhas a \"@cache_readonly\" decorator. When commenting out this cache, this problem disappears. This appears to be a custom decorator implemented in the Pandas code.\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498719082/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498722487",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498722487",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498722487,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODcyMjQ4Nw==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T15:30:55Z",
        "updated_at": "2019-06-04T15:30:55Z",
        "author_association": "MEMBER",
        "body": "Yeah, the output of `is_unique` is computed once and cached for the\nlifetime of the object. Future calls to `is_unique` won't even reach the\nlock, after the value has been cached.\n\nOn Tue, Jun 4, 2019 at 10:22 AM marberi <notifications@github.com> wrote:\n\n> Ok, I got one step further concerning this. The \"is_unique\" method in the\n> Index class found in:\n> pandas/pandas/core/indexes/base.py\n>\n> has a \"@cache_readonly\" decorator. When commenting out this cache, this\n> problem disappears. This appears to be a custom decorator implemented in\n> the Pandas code.\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/dask/dask/issues/4845?email_source=notifications&email_token=AAKAOIVFWHIQQY4DIX7M2ZLPY2CFBA5CNFSM4HPW3SIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW45S2Q#issuecomment-498719082>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAKAOITGSFPVMDLEY52BQVLPY2CFBANCNFSM4HPW3SIA>\n> .\n>\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498722487/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498812977",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498812977",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498812977,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODgxMjk3Nw==",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T19:38:31Z",
        "updated_at": "2019-06-04T19:45:27Z",
        "author_association": "NONE",
        "body": "Would this be an acceptable fix? I tested acquiring locks inside the ```__get__``` method itself and\r\nit did not work. \r\n\r\nhttps://github.com/marberi/pandas/commit/ad33858298961d63ab0bc70caf1d04b3ca02b5fc",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498812977/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498818357",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498818357",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498818357,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODgxODM1Nw==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T19:53:41Z",
        "updated_at": "2019-06-04T19:53:41Z",
        "author_association": "MEMBER",
        "body": "May be worth posting on the pandas issue I linked to. I'm not familiar with\npandas' indexing code.\n\nOn Tue, Jun 4, 2019 at 2:38 PM marberi <notifications@github.com> wrote:\n\n> Would this be an acceptable fix? I tested acquiring locks inside the *get*\n> method itself and\n> it did not work.\n>\n> marberi/pandas@ad33858\n> <https://github.com/marberi/pandas/commit/ad33858298961d63ab0bc70caf1d04b3ca02b5fc>\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/dask/dask/issues/4845?email_source=notifications&email_token=AAKAOITNRWG3PNPRSNXXF7DPY3ADTA5CNFSM4HPW3SIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW5UQMI#issuecomment-498812977>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAKAOISJSOA6YAFCOMG5U6TPY3ADTANCNFSM4HPW3SIA>\n> .\n>\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498818357/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/498822371",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-498822371",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 498822371,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODgyMjM3MQ==",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-04T20:05:29Z",
        "updated_at": "2019-06-04T20:05:29Z",
        "author_association": "NONE",
        "body": "Ok, also posted there. Let's see what they say.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/498822371/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/655815553",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-655815553",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 655815553,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY1NTgxNTU1Mw==",
        "user": {
            "login": "jakirkham",
            "id": 3019665,
            "node_id": "MDQ6VXNlcjMwMTk2NjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jakirkham",
            "html_url": "https://github.com/jakirkham",
            "followers_url": "https://api.github.com/users/jakirkham/followers",
            "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
            "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
            "organizations_url": "https://api.github.com/users/jakirkham/orgs",
            "repos_url": "https://api.github.com/users/jakirkham/repos",
            "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jakirkham/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-07-08T23:51:13Z",
        "updated_at": "2020-07-08T23:51:13Z",
        "author_association": "MEMBER",
        "body": "Is this still an issue, @marberi?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/655815553/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/656122302",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-656122302",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 656122302,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY1NjEyMjMwMg==",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-07-09T13:18:56Z",
        "updated_at": "2020-07-09T13:18:56Z",
        "author_association": "NONE",
        "body": "@jakirkham \r\n\r\nCreating a new environment with:\r\ndask: 2.20.0\r\nnumpy: 1.18.5\r\npandas: 1.0.5\r\n\r\nI can confirm the error is still there. Testing this last year, we could localize\r\nwhere the problem came from, but without determining the best way to \r\ndevelop a fix.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/656122302/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/948780972",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-948780972",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 948780972,
        "node_id": "IC_kwDOAbcwm844jT-s",
        "user": {
            "login": "mprorock",
            "id": 3495140,
            "node_id": "MDQ6VXNlcjM0OTUxNDA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3495140?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mprorock",
            "html_url": "https://github.com/mprorock",
            "followers_url": "https://api.github.com/users/mprorock/followers",
            "following_url": "https://api.github.com/users/mprorock/following{/other_user}",
            "gists_url": "https://api.github.com/users/mprorock/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mprorock/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mprorock/subscriptions",
            "organizations_url": "https://api.github.com/users/mprorock/orgs",
            "repos_url": "https://api.github.com/users/mprorock/repos",
            "events_url": "https://api.github.com/users/mprorock/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mprorock/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-10-21T16:29:18Z",
        "updated_at": "2021-10-21T16:29:18Z",
        "author_association": "NONE",
        "body": "definitely still seeing an issue.  note as a workaround, I was able to specify a single column as a concat of the two values being grouped on and get things to move forward and around the issue\r\n\r\nold code:\r\n```\r\nddf['NEW_VALUE'] = ddf.groupby(['GROUP_KEY_1', 'GROUP_KEY_2'])['value'].cumsum()\r\n```\r\n\r\nnew code to work around the issue:\r\n```\r\nddf['GROUPER'] = ddf['GROUP_KEY_1'].astype(str) + ddf['GROUP_KEY_2'].astype(str)\r\nddf['NEW_VALUE'] = ddf.groupby(['GROUPER'])['value'].cumsum()\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/948780972/reactions",
            "total_count": 2,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 1,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252034871",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-1252034871",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 1252034871,
        "node_id": "IC_kwDOAbcwm85KoIk3",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T08:45:32Z",
        "updated_at": "2022-09-20T08:45:32Z",
        "author_association": "NONE",
        "body": "Reporting another bug, I wanted to test if the problem reported here still is an issue. The code in the original \r\nreport (https://github.com/dask/dask/issues/4845#issue-448576561) appears to work fine using Dask version \r\n2022.9.1 (Linux, Python 3.10.6, Conda). Could someone else confirm this?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252034871/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252077249",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-1252077249",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 1252077249,
        "node_id": "IC_kwDOAbcwm85KoS7B",
        "user": {
            "login": "jakirkham",
            "id": 3019665,
            "node_id": "MDQ6VXNlcjMwMTk2NjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jakirkham",
            "html_url": "https://github.com/jakirkham",
            "followers_url": "https://api.github.com/users/jakirkham/followers",
            "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
            "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
            "organizations_url": "https://api.github.com/users/jakirkham/orgs",
            "repos_url": "https://api.github.com/users/jakirkham/repos",
            "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jakirkham/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T09:21:21Z",
        "updated_at": "2022-09-20T09:21:21Z",
        "author_association": "MEMBER",
        "body": "Yeah am no longer seeing the exception in the original example. Maybe it is worth adding this as a test to Dask (to protect against regression). Would this be of interest to you @marberi?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252077249/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252193520",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-1252193520",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 1252193520,
        "node_id": "IC_kwDOAbcwm85KovTw",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T11:05:59Z",
        "updated_at": "2022-09-20T11:05:59Z",
        "author_association": "NONE",
        "body": "@jakirkham Added a test here:\r\nhttps://github.com/dask/dask/pull/9506\r\n\r\nas mentioned, when running \"pytest\" I could not get it to run the new test. It might\r\nbe something trivial. Tests are still running.\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252193520/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/2004442650",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-2004442650",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 2004442650,
        "node_id": "IC_kwDOAbcwm853eV4a",
        "user": {
            "login": "Giatroo",
            "id": 13424358,
            "node_id": "MDQ6VXNlcjEzNDI0MzU4",
            "avatar_url": "https://avatars.githubusercontent.com/u/13424358?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Giatroo",
            "html_url": "https://github.com/Giatroo",
            "followers_url": "https://api.github.com/users/Giatroo/followers",
            "following_url": "https://api.github.com/users/Giatroo/following{/other_user}",
            "gists_url": "https://api.github.com/users/Giatroo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Giatroo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Giatroo/subscriptions",
            "organizations_url": "https://api.github.com/users/Giatroo/orgs",
            "repos_url": "https://api.github.com/users/Giatroo/repos",
            "events_url": "https://api.github.com/users/Giatroo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Giatroo/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-03-18T16:52:26Z",
        "updated_at": "2024-03-18T16:52:26Z",
        "author_association": "NONE",
        "body": "Few years later, and this is still an error. I'm using Dask 2023.7.1 and this error happened to me. It was a pain in the ass to finally see that this is a stochastic behavior and sometimes the code works and sometimes it doesn't. Even trying Dask 2024.3.1 (which is the latest at the point I'm writing this), this still happens.\r\n\r\n\r\nDoes someone have an update on this error? How can an issue be open for such a long time? =/ ",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/2004442650/reactions",
            "total_count": 1,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 1
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/2009282342",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-2009282342",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 2009282342,
        "node_id": "IC_kwDOAbcwm853wzcm",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-03-20T10:56:17Z",
        "updated_at": "2024-03-20T10:56:17Z",
        "author_association": "NONE",
        "body": "Not from my side. Hopefully this gets fixed.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/2009282342/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/2018274229",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-2018274229",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 2018274229,
        "node_id": "IC_kwDOAbcwm854TGu1",
        "user": {
            "login": "phofl",
            "id": 61934744,
            "node_id": "MDQ6VXNlcjYxOTM0NzQ0",
            "avatar_url": "https://avatars.githubusercontent.com/u/61934744?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/phofl",
            "html_url": "https://github.com/phofl",
            "followers_url": "https://api.github.com/users/phofl/followers",
            "following_url": "https://api.github.com/users/phofl/following{/other_user}",
            "gists_url": "https://api.github.com/users/phofl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/phofl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/phofl/subscriptions",
            "organizations_url": "https://api.github.com/users/phofl/orgs",
            "repos_url": "https://api.github.com/users/phofl/repos",
            "events_url": "https://api.github.com/users/phofl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/phofl/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-03-25T15:26:38Z",
        "updated_at": "2024-03-25T15:26:38Z",
        "author_association": "MEMBER",
        "body": "@Giatroo do you have a reproducer? The initial example works now",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/2018274229/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/2020497659",
        "html_url": "https://github.com/dask/dask/issues/4845#issuecomment-2020497659",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/4845",
        "id": 2020497659,
        "node_id": "IC_kwDOAbcwm854blj7",
        "user": {
            "login": "Giatroo",
            "id": 13424358,
            "node_id": "MDQ6VXNlcjEzNDI0MzU4",
            "avatar_url": "https://avatars.githubusercontent.com/u/13424358?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Giatroo",
            "html_url": "https://github.com/Giatroo",
            "followers_url": "https://api.github.com/users/Giatroo/followers",
            "following_url": "https://api.github.com/users/Giatroo/following{/other_user}",
            "gists_url": "https://api.github.com/users/Giatroo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Giatroo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Giatroo/subscriptions",
            "organizations_url": "https://api.github.com/users/Giatroo/orgs",
            "repos_url": "https://api.github.com/users/Giatroo/repos",
            "events_url": "https://api.github.com/users/Giatroo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Giatroo/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-03-26T13:55:55Z",
        "updated_at": "2024-03-26T13:55:55Z",
        "author_association": "NONE",
        "body": "The initial example still doesn't work. You just have to make a few tries, since it's an error that appears randomly. \r\n\r\nHere's a print of an env I've just created by installing `dask[dataframe]` on the latest version.\r\n\r\n![image](https://github.com/dask/dask/assets/13424358/1cd58988-58cd-4fb0-9a44-030b809860c6)\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/2020497659/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]