[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/522555063",
        "html_url": "https://github.com/dask/dask/issues/5292#issuecomment-522555063",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5292",
        "id": 522555063,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyMjU1NTA2Mw==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-19T12:42:04Z",
        "updated_at": "2019-08-19T12:42:04Z",
        "author_association": "MEMBER",
        "body": "Can you check your example? I get a TypeError on \r\n\r\n```\r\n>>> df2 = df2 = pd.concat(df1+1, df1+2)\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/522555063/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/522557058",
        "html_url": "https://github.com/dask/dask/issues/5292#issuecomment-522557058",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5292",
        "id": 522557058,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyMjU1NzA1OA==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-19T12:46:41Z",
        "updated_at": "2019-08-19T12:46:41Z",
        "author_association": "MEMBER",
        "body": "Assuming you meant `df2 = pd.concat([df1 + 1, df1 + 2])` in `merge_chunk`, this looks a little fishy\r\n\r\n```\r\nipdb> pp func\r\n<function merge_chunk at 0x117225400>\r\nipdb> pp args\r\n(   a1  a2  a3\r\n0   1   3   3,\r\n    a1  a2  a3\r\n0   2   4   4\r\n0   3   5   5\r\n1   5   3   7\r\n1   6   4   8)\r\nipdb> pp kwargs\r\n{'empty_index_dtype': dtype('int64'),\r\n 'how': 'left',\r\n 'indicator': False,\r\n 'left_index': False,\r\n 'left_on': 'a1',\r\n 'on': None,\r\n 'right_index': True,\r\n 'right_on': None,\r\n 'suffixes': ['_l', '_r']}\r\n\r\n```\r\n\r\nI would have expected that at be `'on': \"a1\"` or both `left_on` and `right_on` to be `'a1'`. @sighingnow are you interested in debugging this further?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/522557058/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/522596297",
        "html_url": "https://github.com/dask/dask/issues/5292#issuecomment-522596297",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5292",
        "id": 522596297,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyMjU5NjI5Nw==",
        "user": {
            "login": "sighingnow",
            "id": 7144772,
            "node_id": "MDQ6VXNlcjcxNDQ3NzI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7144772?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/sighingnow",
            "html_url": "https://github.com/sighingnow",
            "followers_url": "https://api.github.com/users/sighingnow/followers",
            "following_url": "https://api.github.com/users/sighingnow/following{/other_user}",
            "gists_url": "https://api.github.com/users/sighingnow/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/sighingnow/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sighingnow/subscriptions",
            "organizations_url": "https://api.github.com/users/sighingnow/orgs",
            "repos_url": "https://api.github.com/users/sighingnow/repos",
            "events_url": "https://api.github.com/users/sighingnow/events{/privacy}",
            "received_events_url": "https://api.github.com/users/sighingnow/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-19T14:19:35Z",
        "updated_at": "2019-08-19T14:19:35Z",
        "author_association": "NONE",
        "body": "> `>>> df2 = df2 = pd.concat(df1+1, df1+2)`\r\n\r\nSorry for the typo and I have updated the description. It should be `df2 = pd.concat([df1 + 1, df1 + 2])`.\r\n\r\n@TomAugspurger For more information about the bug, we first noticed a strange behavior of **pandas** when developing mars (a distributed numpy/pandas engine like dask), and we then noticed that dask also failed to handle this case. We considered that pandas is well tested so we thought the behavior is by-design and didn't report it to pandas.\r\n\r\nYou can find a detailed note here:\r\n\r\nhttps://github.com/mars-project/mars/blob/5bf608d3ff76026bfc2e808e874150ff0f1f22ea/mars/dataframe/merge/tests/test_merge_execution.py#L144-L177",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/522596297/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/522987572",
        "html_url": "https://github.com/dask/dask/issues/5292#issuecomment-522987572",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5292",
        "id": 522987572,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyMjk4NzU3Mg==",
        "user": {
            "login": "sighingnow",
            "id": 7144772,
            "node_id": "MDQ6VXNlcjcxNDQ3NzI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7144772?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/sighingnow",
            "html_url": "https://github.com/sighingnow",
            "followers_url": "https://api.github.com/users/sighingnow/followers",
            "following_url": "https://api.github.com/users/sighingnow/following{/other_user}",
            "gists_url": "https://api.github.com/users/sighingnow/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/sighingnow/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sighingnow/subscriptions",
            "organizations_url": "https://api.github.com/users/sighingnow/orgs",
            "repos_url": "https://api.github.com/users/sighingnow/repos",
            "events_url": "https://api.github.com/users/sighingnow/events{/privacy}",
            "received_events_url": "https://api.github.com/users/sighingnow/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-20T12:17:52Z",
        "updated_at": "2019-08-20T12:17:52Z",
        "author_association": "NONE",
        "body": ">  would have expected that at be 'on': \"a1\" or both left_on and right_on to be 'a1'. \r\n\r\n@TomAugspurger That is not correct and the dask behavior is consistent with pandas, it [says](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html):\r\n\r\n> on: Column or index level name(s) in **the caller** to join on the index in other",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/522987572/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/523001396",
        "html_url": "https://github.com/dask/dask/issues/5292#issuecomment-523001396",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5292",
        "id": 523001396,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyMzAwMTM5Ng==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-20T12:56:04Z",
        "updated_at": "2019-08-20T12:56:04Z",
        "author_association": "MEMBER",
        "body": "Yes, I misread the original example as pd.merge, rather than DataFrame.join.\n\nOn Tue, Aug 20, 2019 at 7:17 AM Tao He <notifications@github.com> wrote:\n\n> would have expected that at be 'on': \"a1\" or both left_on and right_on to\n> be 'a1'.\n>\n> @TomAugspurger <https://github.com/TomAugspurger> That is not correct and\n> the dask behavior is consistent with pandas, it says\n> <https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html>\n> :\n>\n> on: Column or index level name(s) in *the caller* to join on the index in\n> other\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/dask/dask/issues/5292?email_source=notifications&email_token=AAKAOIUFE37G5AWB4GAFHWTQFPOHHA5CNFSM4IM4XFE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4WCQNA#issuecomment-522987572>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAKAOIWIIN64Z6PF2S3VWATQFPOHHANCNFSM4IM4XFEQ>\n> .\n>\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/523001396/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/531521789",
        "html_url": "https://github.com/dask/dask/issues/5292#issuecomment-531521789",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5292",
        "id": 531521789,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUzMTUyMTc4OQ==",
        "user": {
            "login": "arpit1997",
            "id": 10682054,
            "node_id": "MDQ6VXNlcjEwNjgyMDU0",
            "avatar_url": "https://avatars.githubusercontent.com/u/10682054?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/arpit1997",
            "html_url": "https://github.com/arpit1997",
            "followers_url": "https://api.github.com/users/arpit1997/followers",
            "following_url": "https://api.github.com/users/arpit1997/following{/other_user}",
            "gists_url": "https://api.github.com/users/arpit1997/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/arpit1997/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/arpit1997/subscriptions",
            "organizations_url": "https://api.github.com/users/arpit1997/orgs",
            "repos_url": "https://api.github.com/users/arpit1997/repos",
            "events_url": "https://api.github.com/users/arpit1997/events{/privacy}",
            "received_events_url": "https://api.github.com/users/arpit1997/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-09-14T23:38:19Z",
        "updated_at": "2019-09-14T23:38:19Z",
        "author_association": "CONTRIBUTOR",
        "body": "@TomAugspurger \r\n\r\n```\r\nimport pandas as pd\r\ndf1 = pd.DataFrame([[1,3,3], [4,2,6], [7, 8, 9]], columns=['a1', 'a2', 'a3'])\r\ndf2 = pd.concat([df1+1, df1+2])\r\nsdsd = df1.merge(df2, how='left', left_on='a1', suffixes=('r', 's'), left_index=False, right_index=True, indicator=False)\r\n\r\nOutput:\r\n\r\n\r\n   a1r  a2r  a3r  a1s  a2s  a3s\r\n0    1    1    1    1    1    1\r\n1    1    1    1    1    1    1\r\n```\r\n\r\nThis behaviour might just be from pandas instead of dask. \r\nDon't know how to proceed further on this.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/531521789/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/531963407",
        "html_url": "https://github.com/dask/dask/issues/5292#issuecomment-531963407",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5292",
        "id": 531963407,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUzMTk2MzQwNw==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-09-16T21:21:40Z",
        "updated_at": "2019-09-16T21:21:47Z",
        "author_association": "MEMBER",
        "body": "@arpit1997 what version of pandas gives that output? On pandas master I have\r\n\r\n```python\r\n   a1  a1r  a2r  a3r  a1s  a2s  a3s\r\n0   1    1    3    3  5.0  3.0  7.0\r\n0   1    1    3    3  6.0  4.0  8.0\r\n1   4    4    2    6  NaN  NaN  NaN\r\n2   7    7    8    9  NaN  NaN  NaN\r\n\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/531963407/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/531968122",
        "html_url": "https://github.com/dask/dask/issues/5292#issuecomment-531968122",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5292",
        "id": 531968122,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUzMTk2ODEyMg==",
        "user": {
            "login": "arpit1997",
            "id": 10682054,
            "node_id": "MDQ6VXNlcjEwNjgyMDU0",
            "avatar_url": "https://avatars.githubusercontent.com/u/10682054?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/arpit1997",
            "html_url": "https://github.com/arpit1997",
            "followers_url": "https://api.github.com/users/arpit1997/followers",
            "following_url": "https://api.github.com/users/arpit1997/following{/other_user}",
            "gists_url": "https://api.github.com/users/arpit1997/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/arpit1997/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/arpit1997/subscriptions",
            "organizations_url": "https://api.github.com/users/arpit1997/orgs",
            "repos_url": "https://api.github.com/users/arpit1997/repos",
            "events_url": "https://api.github.com/users/arpit1997/events{/privacy}",
            "received_events_url": "https://api.github.com/users/arpit1997/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-09-16T21:36:52Z",
        "updated_at": "2019-09-16T21:40:18Z",
        "author_association": "CONTRIBUTOR",
        "body": "@TomAugspurger I am  extremely sorry. I accidentally posted the wrong result. Here is the correct one. Pandas version: 0.25.1\r\n\r\n```\r\nimport pandas as pd\r\ndf1 = pd.DataFrame([[1,3,3], [4,2,6], [7, 8, 9]], columns=['a1', 'a2', 'a3'])\r\ndf2 = pd.concat([df1+1, df1+2])\r\n\r\nsdsd = df1.merge(df2, how='left', left_on='a1', suffixes=('r', 's'), left_index=False, right_index=True, indicator=False)\r\n\r\n   a1  a1r  a2r  a3r  a1s  a2s  a3s\r\n0   1    1    3    3  5.0  3.0  7.0\r\n0   1    1    3    3  6.0  4.0  8.0\r\n1   4    4    2    6  NaN  NaN  NaN\r\n2   7    7    8    9  NaN  NaN  NaN\r\n```\r\n\r\nProblem is that its metadata in Dask DataFrame is \r\n\r\n```\r\n   a1r  a2r  a3r  a1s  a2s  a3s\r\n0    1    1    1    1    1    1\r\n1    1    1    1    1    1    1\r\n```\r\n\r\nMetadata DFs\r\n\r\n```\r\ndf3 = pd.DataFrame.from_dict({'a1': {0: 1, 1: 1}, 'a2': {0: 1, 1: 1}, 'a3': {0: 1, 1: 1}})\r\ndf4 = pd.DataFrame.from_dict({'a1': {1: 1, 2: 1}, 'a2': {1: 1, 2: 1}, 'a3': {1: 1, 2: 1}})\r\nsdsd = df3.merge(df4, how='left', left_on='a1', suffixes=('r', 's'), left_index=False, right_index=True, indicator=False)\r\n```\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/531968122/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]